repos:

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: "v0.12.7" 
  hooks:
    - id: ruff
      language: python
      language_version: python3.12
      args: [--fix, --exit-non-zero-on-fix]
