[tool.pytest.ini_options]
testpaths = ["wisent_guard/tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = ["-v", "--tb=short", "--ignore=evaluation", "-m", "not heavy and not docker"]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "heavy: marks tests as very resource-intensive with large model downloads (deselect with '-m \"not heavy\"')",
    "model_download: marks tests that download models from HuggingFace (deselect with '-m \"not model_download\"')",
    "integration: marks tests as integration tests",
    "unit: marks tests as unit tests",
    "docker: marks tests for Docker-based execution",
    "performance: marks tests for performance evaluation",
    "cli: marks tests for CLI integration",
]
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore::PendingDeprecationWarning",
]