"""
Overflow named constants for the wisent package (part 6).
Imported by _constants_part5.py via star-import so all constants remain
accessible from wisent.core.constants.
"""
from wisent.core.grp_05._constants_part7 import *  # noqa: F401,F403

# --- Adaptive cross-validation parameters ---
ADAPTIVE_CV_MIN_FOLDS = 2
ADAPTIVE_CV_MAX_FOLDS = 5
ADAPTIVE_CV_SAMPLES_PER_FOLD = 10

# --- Adaptive MLP probe hidden dimensions ---
ADAPTIVE_MLP_HIDDEN_MIN = 16
ADAPTIVE_MLP_HIDDEN_MAX = 256

# --- Adaptive manifold components ---
ADAPTIVE_MANIFOLD_MAX_COMPONENTS = 15

# --- Adaptive permutation parameters ---
ADAPTIVE_PERMUTATIONS_MIN = 50
ADAPTIVE_PERMUTATIONS_MAX = 200
ADAPTIVE_PERMUTATIONS_DIVISOR = 5000

# --- KNN adaptive k ---
KNN_ADAPTIVE_K_MIN = 3
KNN_ADAPTIVE_K_DIVISOR = 4

# --- MLP probe early stopping ---
MLP_EARLY_STOPPING_MIN_SAMPLES = 20
MLP_PROBE_MAX_ITER = 500

# --- UMAP adaptive neighbors ---
UMAP_NEIGHBORS_MIN = 5
UMAP_NEIGHBORS_MAX = 15
UMAP_NEIGHBORS_DIVISOR = 20

# --- PaCMAP adaptive neighbors ---
PACMAP_NEIGHBORS_MIN = 5
PACMAP_NEIGHBORS_MAX = 15
PACMAP_NEIGHBORS_DIVISOR = 4
PACMAP_N_COMPONENTS_DEFAULT = 10
PACMAP_MN_RATIO_DEFAULT = 0.5
PACMAP_FP_RATIO_DEFAULT = 2.0
PACMAP_NUM_ITERS_DEFAULT = 50

# --- Spectral clustering (used across concept analysis) ---
SPECTRAL_N_NEIGHBORS_DEFAULT = 10

# --- Cone scoring weights ---
CONE_NOISE_SCALE = 0.3
CONE_LOSS_WEIGHT_DISSIMILAR = 0.5
CONE_LOSS_WEIGHT_CONE = 0.5
CONE_LOSS_WEIGHT_DIVERSITY = 0.1
CONE_POS_RATIO_WEIGHT = 0.7
CONE_SIG_RATIO_WEIGHT = 0.3
CONE_COS_THRESHOLD_LOW = 0.3
CONE_COS_SCORE_LOW = 0.5
CONE_COS_THRESHOLD_HIGH = 0.7
CONE_SIGNIFICANCE_THRESHOLD = 0.1
CONE_WEIGHT_COS = 0.20
CONE_WEIGHT_SIG = 0.25
CONE_WEIGHT_EFFECT = 0.20
CONE_WEIGHT_SAMPLE = 0.20
CONE_WEIGHT_RATIO = 0.15

# --- Geometry detector scoring ---
DETECTOR_COHENS_D_DIVISOR = 5
DETECTOR_LARGE_SAMPLE_N = 50
DETECTOR_CONE_THRESHOLD_LOW = 0.1
DETECTOR_CONE_RANGE_MID = 0.3
DETECTOR_CONE_SCALE_MID = 0.2
DETECTOR_CONE_RANGE_HIGH = 0.7
DETECTOR_CONE_SCALE_HIGH = 0.4
DETECTOR_CONE_OFFSET_TOP = 0.8
DETECTOR_CONE_RANGE_TOP = 0.7
DETECTOR_CONE_SCALE_TOP = 0.3
DETECTOR_SMALL_SAMPLE_N = 20
DETECTOR_CLUSTER_SAMPLE_N = 30

# --- Subspace validation dynamic thresholds ---
SUBSPACE_NORM_TOLERANCE = 0.05
SUBSPACE_SPECTRAL_RATIO_LOW = 0.1
SUBSPACE_SPECTRAL_RATIO_HIGH = 0.2
SUBSPACE_VAR_THRESHOLD_MAX = 0.95
SUBSPACE_VAR_THRESHOLD_ADJUST = 0.1
SUBSPACE_CONE_MIN_DYNAMIC = 0.5
SUBSPACE_CONE_ADJUST = 0.1
SUBSPACE_VAR_THRESHOLD_MIN = 0.75
SUBSPACE_VAR_FINE_ADJUST = 0.05
SUBSPACE_HIDDEN_DIM_LARGE = 4096
SUBSPACE_SILHOUETTE_MIN_DYNAMIC = 0.4
SUBSPACE_SILHOUETTE_ADJUST = 0.1

# --- Diagnostic significance markers ---
DIAG_SIGNIFICANCE_STRONG = 0.3
DIAG_SIGNIFICANCE_MODERATE = 0.1
DIAG_SIGNIFICANCE_WEAK = 0.05
DIAG_SCORE_HIGH = 0.8
DIAG_SCORE_MODERATE = 0.6
DIAG_SCORE_LOW = 0.4

# --- Diagnose vectors thresholds ---
DIAG_NORM_TOLERANCE = 0.01
DIAG_ZERO_PCT_THRESHOLD = 50
DIAG_MEAN_MAGNITUDE_THRESHOLD = 0.5
DIAG_NORM_MIN = 0.01
DIAG_NORM_MAX = 100

# --- Marketplace quality scoring ---
MARKETPLACE_QUALITY_MAX = 0.80
MARKETPLACE_QUALITY_BASE = 0.60
MARKETPLACE_QUALITY_INCREMENT = 0.05
MARKETPLACE_QUALITY_DEFAULT = 0.55

# --- Decomposition PCA ---
DECOMP_PCA_DIMS_MAX = 50
DECOMP_KMEANS_N_INIT_MIN = 3
DECOMP_KMEANS_N_INIT_MAX = 10
DECOMP_KMEANS_SCALING_FACTOR = 1000

# --- Cloud metrics ---
CLOUD_VAR_PERCENTILE_50 = 0.5
CLOUD_VAR_PERCENTILE_90 = 0.9
CLOUD_VAR_PERCENTILE_99 = 0.99
CLOUD_K_NEIGHBORS_DEFAULT = 10

# --- Intrinsic dim top eigenvalues ---
INTRINSIC_DIM_TOP_N = 10

# --- Visualization positioning ---
VIZ_TEXT_BOX_LEFT = 0.02
VIZ_TEXT_BOX_RIGHT = 0.98
VIZ_TEXT_BOX_CENTER = 0.5
VIZ_CONTOURF_LEVEL = 0.5
VIZ_MOVEMENT_SCALE = 0.8
VIZ_ARROW_HEAD_LENGTH = 0.1
VIZ_ARROW_HEAD_WIDTH = 0.05

# --- Steering autotuner ---
AUTOTUNER_ACCURACY_DECREMENT = 0.01
AUTOTUNER_ACCURACY_FILTER = 0.5

# --- Steering layer bounds ---
STEERING_LOSS_MARGIN = 0.5

# --- Multi-layer improvement ---
MULTI_LAYER_IMPROVEMENT_THRESHOLD = 0.05
MULTI_LAYER_AGREEMENT_THRESHOLD = 0.8

# --- Logistic regression bounds ---
GEOMETRY_LOGISTIC_C_MIN = 0.01
GEOMETRY_LOGISTIC_C_MAX = 10.0

# --- Docker resource limits ---
DOCKER_PIDS_LIMIT = 256
SAFE_DOCKER_NPROC_DEFAULT = 64

# --- Agent synthetic pair generation ---
AGENT_SYNTH_MIN_PAIRS = 5
AGENT_SYNTH_TIME_MULTIPLIER = 3
AGENT_SYNTH_TOKENS_PER_PAIR = 150
AGENT_SYNTH_BASE_TOKENS = 500

# --- Parser optimization defaults ---
PARSER_DEFAULT_SAMPLE_LIMIT = 100
PARSER_DEFAULT_MAX_ITERATIONS = 10
PARSER_DEFAULT_NOISE_SCALE = 0.1
PARSER_DEFAULT_NUM_STRENGTHS = 10
PARSER_DEFAULT_MAX_TIME_MINUTES = 60.0

# --- Parser continual learning defaults ---
PARSER_CONTINUAL_MAX_CYCLES = 100
PARSER_CONTINUAL_EWC_LAMBDA = 1000.0
PARSER_CONTINUAL_REPLAY_SIZE = 50
PARSER_CONTINUAL_REPLAY_INTERVAL = 5
PARSER_CONTINUAL_FORGETTING_THRESHOLD = 0.9
PARSER_CONTINUAL_CONVERGENCE_WINDOW = 10

# --- Parser Optuna defaults ---
PARSER_OPTUNA_TRIALS = 300
PARSER_OPTUNA_STARTUP_TRIALS = 10
PARSER_OPTUNA_EARLY_STOP_PATIENCE = 10
PARSER_OPTUNA_NUM_PAIRS = 100

# --- Parser full optimize defaults ---
PARSER_FULL_OPTIMIZE_TRIALS = 50
PARSER_FULL_OPTIMIZE_MIN_QUALITY = 2
PARSER_FULL_OPTIMIZE_MAX_TIME = 20.0
PARSER_FULL_OPTIMIZE_SAMPLE_SIZES = (5, 10, 20, 50, 100, 200, 500)
PARSER_FULL_OPTIMIZE_STRENGTHS = (0.5, 1.0, 1.5, 2.0)

# --- Evaluation refusal parser ---
EVAL_REFUSAL_MAX_TOKENS = 150

# --- Verify steering parser ---
VERIFY_STEERING_THRESHOLD = 0.3

# --- Geometry search parser ---
GEOMETRY_SEARCH_LIMIT = 50
GEOMETRY_SEARCH_PARAM_COUNT = 3

# --- Diagnose vectors parser ---
DIAG_PARSER_THRESHOLD = 0.7
DIAG_PARSER_COUNT_SMALL = 5
DIAG_PARSER_COUNT_LARGE = 10

# --- Optimize sample size parser ---
OPTIMIZE_SAMPLE_TEST_SIZE = 200
OPTIMIZE_SAMPLE_TEST_SPLIT = 0.2

# --- Cluster benchmarks ---
CLUSTER_PROGRESS_INTERVAL = 20
CLUSTER_MIN_PAIRS = 10
CLUSTER_PROMPT_TRUNCATION = 500
CLUSTER_RESPONSE_TRUNCATION = 200

# --- Steering method architectural ---
GATING_HIDDEN_DIM_DIVISOR = 2
MIN_CONCEPT_DIM_DEFAULT = 2

# --- Math perturbation ---
MATH_NUMBER_PERTURBATION_OFFSET = 0.25

# --- Desklib detector ---
DESKLIB_MAX_LENGTH = 768

# --- EOT survival ratio clamping ---
EOT_SURVIVAL_MIN_RATIO = 1.0

# --- Binary variance (stability analysis) ---
STABILITY_BINARY_VARIANCE = 0.5
