"""Constants that cannot be experimentally optimized."""
from wisent.core.grp_05.sub_constants.cannot_be_optimized._fixed_02 import *  # noqa: F401,F403

DEFAULT_RANDOM_SEED = 42
DEFAULT_LIMIT = 100
DEFAULT_SHOW_COMPARISONS = 0
CLASSIFIER_BATCH_SIZE = 32
MAX_REGENERATION_ATTEMPTS = 3

# --- Geometry / visualization ---
VIZ_PCA_COMPONENTS = 50
VIZ_MAX_SAMPLES = 200
VIZ_PERPLEXITY = 30
VIZ_N_NEIGHBORS = 15
VIZ_MIN_DIST = 0.1
VIZ_N_NEIGHBORS_TRIMAP = 10
VIZ_NUM_ITERS = 50
VIZ_PCA_DIMS_TRIMAP = 30
VIZ_LIMIT = 200

# --- Statistical testing ---
N_BOOTSTRAP = 10

# --- Continual learning ---
REPLAY_BUFFER_MAX_SIZE = 200

# --- Data loading ---
DATA_LOAD_LIMIT = 200
DATA_CHUNK_SIZE = 50
NONSENSE_N_PAIRS = 50

# --- Agent ---
AGENT_MAX_WORKERS = 4
AGENT_CLASSIFIER_EPOCHS = 50

# --- Docker / sandbox ---
FEEDBACK_MAX_CHARS = 2000

# --- Multimodal ---
VIDEO_KEYFRAME_INTERVAL = 4
VIDEO_NUM_FRAMES = 16
VIDEO_FRAME_SAMPLE_RATE = 4
# --- Timing ---
TIMING_SAMPLES_PER_TASK = 1000

# --- Pairs generation ---
PAIRS_NUM_PAIRS = 100
PAIRS_MIN_LENGTH = 100
PAIRS_MAX_LENGTH = 500
# --- Geometry search ---
GEO_PAIRS_PER_BENCHMARK = 50
GEO_MAX_LAYER_COMBO_SIZE = 3
GEO_ESTIMATED_TIME_PER_EXTRACTION = 120.0
WM_BRANDING_WIDTH = 48
MAX_COMBINATIONS = 1000
TRACKING_SAMPLING_INTERVAL = 0.1
MAX_DEPTH = 3

# --- Cache ---
KEEP_RECENT_HOURS_DEFAULT = 24.0

# --- Visualization ---
TSNE_N_ITER = 1000
VIZ_DPI = 150
TECZA_LOGGING_INTERVAL = 10
TETNO_CONDITION_LOGGING_INTERVAL = 20

# --- HuggingFace upload retry ---
HF_UPLOAD_MAX_RETRIES = 8
HF_UPLOAD_BASE_WAIT = 120
HF_UPLOAD_BACKOFF_MAX_EXPONENT = 3
HF_UPLOAD_JITTER_MIN = 0.5
HF_UPLOAD_JITTER_MAX = 1.5

# --- Classifier training ---
# CLASSIFIER_TEST_SIZE defined in _arb_01 (=0.2)

# --- Viz steering method presets ---
VIZ_PROJECTION_COMPONENTS = 5
VIZ_REPLACEMENT_BLEND = 0.5
VIZ_MLP_EPOCHS = 100
VIZ_CLAMPING_MARGIN = 0.1

GROM_CREATE_LOG_INTERVAL = 50

# --- Training logging ---
TRAINING_LOG_INTERVAL = 20

# --- Visualization positioning ---
VIZ_TEXT_BOX_LEFT = 0.02
VIZ_TEXT_BOX_RIGHT = 0.98
VIZ_CONTOURF_LEVEL = 0.5
VIZ_MOVEMENT_SCALE = 0.8
VIZ_ARROW_HEAD_LENGTH = 0.1
VIZ_ARROW_HEAD_WIDTH = 0.05

# --- Math perturbation ---
MATH_NUMBER_PERTURBATION_OFFSET = 0.25

# --- Visualization mesh grids ---
VIZ_MESHGRID_RESOLUTION_HIGH = 200
VIZ_MESHGRID_RESOLUTION_MED = 100
VIZ_HISTOGRAM_BINS = 30
HEATMAP_TEXT_CONTRAST_THRESHOLD = 0.5
SAFE_DOCKER_FSIZE_MB = 10
SAFE_DOCKER_NOFILE = 128
# --- Separator widths (print formatting) ---
SEPARATOR_WIDTH_COMPACT = 30
SEPARATOR_WIDTH_HALF = 35
SEPARATOR_WIDTH_NARROW = 40
SEPARATOR_WIDTH_MEDIUM = 50
SEPARATOR_WIDTH_MEDIUM_PLUS = 55
SEPARATOR_WIDTH_TABLE = 56
SEPARATOR_WIDTH_STANDARD = 60
SEPARATOR_WIDTH_PLUS = 65
SEPARATOR_WIDTH_WIDE = 70
SEPARATOR_WIDTH_WIDE_PLUS = 75
SEPARATOR_WIDTH_REPORT = 80
SEPARATOR_WIDTH_SENSITIVITY = 89
SEPARATOR_WIDTH_FULL = 100
SEPARATOR_WIDTH_ULTRA = 128
SEPARATOR_WIDTH_MAX = 150
SEPARATOR_PAD_SMALL = 20
# --- Display decimal precision ---
DISPLAY_DECIMAL_PRECISION = 2
# --- Progress logging intervals ---
PROGRESS_LOG_INTERVAL_10 = 10
PROGRESS_LOG_INTERVAL_20 = 20
# --- Visualization font sizes (additional) ---
VIZ_FONTSIZE_TINY = 7
VIZ_FONTSIZE_BODY = 10
VIZ_FONTSIZE_SUBTITLE = 12
# --- Visualization line widths (additional) ---
VIZ_LINEWIDTH_FINE = 0.5
VIZ_LINEWIDTH_HAIRLINE = 1
# --- Visualization colorbar ---
VIZ_COLORBAR_FRACTION = 0.046
VIZ_COLORBAR_PAD = 0.04
# --- Visualization suptitle y-offset ---
VIZ_SUPTITLE_Y_OFFSET = 1.01
VIZ_SUPTITLE_Y_OFFSET_HIGH = 1.02
# --- Heatmap accuracy bounds ---
VIZ_HEATMAP_ACCURACY_VMIN = 0.5
VIZ_HEATMAP_ACCURACY_VMAX = 1.0
# --- Histogram alpha ---
VIZ_HISTOGRAM_ALPHA = 0.5
# --- Scale/split defaults ---
SPLIT_RATIO_FULL = 1.0
DEFAULT_SCALE_FACTOR = 1.0
# --- Single-threaded job count ---
N_JOBS_SINGLE = 1
# --- Visualization alpha values (additional) ---
VIZ_ALPHA_HIST = 0.4
# --- Contrastive pair limits ---
MAX_INCORRECT_PER_CORRECT = 2
# --- Evidence train/test split fraction ---
EVIDENCE_TRAIN_SPLIT_NUM = 2
EVIDENCE_TRAIN_SPLIT_DEN = 3
# --- Visualization line plot marker sizes ---
VIZ_MARKERSIZE_LINE_SMALL = 6
VIZ_MARKERSIZE_LINE = 8
# --- Database connection retries ---
DB_CONNECTION_MAX_RETRIES = 5
# --- Cache configuration ---
CACHE_CHUNK_SIZE = 25
CACHE_MAX_AGE_DAYS = 30
# --- HTTP request timeouts ---
HTTP_TIMEOUT_MEDIUM = 30
HTTP_TIMEOUT_LONG = 60
# --- Gibberish generation ranges ---
GIBBERISH_WORD_COUNT_MIN = 10
GIBBERISH_WORD_COUNT_MAX = 30
GIBBERISH_WORD_LEN_MIN = 3
GIBBERISH_WORD_LEN_MAX = 12
GIBBERISH_LINE_COUNT_MIN = 3
GIBBERISH_LINE_COUNT_MAX = 8
# --- Perturbation ranges ---
PERTURB_UP_MIN = 1.1
PERTURB_UP_MAX = 1.5
PERTURB_DOWN_MIN = 0.5
PERTURB_DOWN_MAX = 0.9
YEAR_SHIFT_MIN = -50
YEAR_SHIFT_MAX = 50
YEAR_SHIFT_DEFAULT = 10
SMALL_NUM_INCREMENT_MIN = 1
SMALL_NUM_INCREMENT_MAX = 5
NUM_PERTURB_SCALE_MIN = 0.5
NUM_PERTURB_SCALE_MAX = 1.5
YEAR_PERTURB_LARGE = 10
YEAR_PERTURB_SMALL = 5
# --- HaluLens content thresholds ---
HALULENS_MIN_CONTENT_LENGTH = 200
HALULENS_SENT_LEN_MIN = 30
HALULENS_SENT_LEN_MAX = 300
# --- STSB score ---
STSB_SCORE_NEUTRAL = 0.1
# --- SimpleQA thresholds ---
SIMPLEQA_MIN_CHAR_LENGTH = 3
SIMPLEQA_MAX_ANSWER_LENGTH = 50
# --- C4 text thresholds ---
C4_MIN_TEXT_LENGTH = 50
# --- Paloma text chunking ---
PALOMA_DOCS_DIVISOR = 4
PALOMA_MIN_TEXT_LENGTH = 200
PALOMA_CHUNK_SIZE_WORDS = 200
PALOMA_TARGET_PAIRS_PER_DOC = 4
PALOMA_MIN_CHUNK_WORDS = 50
PALOMA_MAX_WORDS = 200
PALOMA_MAX_CHARS = 1000
PALOMA_MIN_WORDS = 10
# --- Translation shuffle attempts ---
TRANSLATION_MAX_SHUFFLE_ATTEMPTS = 10
# --- Math parsing ---
MATH_SHORT_VAR_MAX_LEN = 2
# --- Bias detection ---
BIAS_LIBERAL_THRESHOLD = 3
# --- RoBERTa API ---
ROBERTA_API_DEFAULT_WAIT_TIME = 20
ROBERTA_API_MAX_WAIT_TIME = 30
DOCKER_CPU_QUOTA_50PCT_US = 50000
# --- Visualization DPI ---
VIZ_DPI_STANDARD = 120
VIZ_DPI_LOW = 100
# --- Visualization marker sizes ---
VIZ_CENTROID_MARKER_SIZE = 200
VIZ_CENTROID_MARKER_SIZE_ALT = 150
VIZ_X_MARKER_SIZE = 100
VIZ_HEATMAP_ASTERISK_SIZE = 200
# --- Visualization figure dimensions ---
VIZ_FIGURE_WIDTH_PX = 1000
