# TruthfulQA MC2 - Truthfulness evaluation with multiple correct answers
task_name: truthfulqa_mc2
description: Tests model truthfulness allowing multiple correct answers

evaluation:
  type: multiple_choice
  method: loglikelihood
  output_type: multiple_choice

metrics:
  primary: acc
  all:
    - acc        # Accuracy

aggregation: mean

task_config:
  num_choices: variable  # Varies per question
  choice_format: text
  targets_field: mc2_targets
  choices_field: choices
  labels_field: labels
  question_field: question

notes: |
  - Multiple correct answers allowed (mc2 = multiple choice 2+ correct)
  - 817 validation questions (same questions as mc1, different scoring)
  - More lenient than mc1
  - Variable number of choices per question
