name: CI

on:
  push:                # any branch push
  pull_request:        # any PR
  workflow_dispatch:   # manual “Run workflow” button

# The default workflow token stays read‑only;
# we rely on the PAT for every write.
permissions:
  contents: read

jobs:
# ──────────────────────────────────────────────────────────────
# 1. LINT  – Ruff check, optional auto‑fix, optional commit
# ──────────────────────────────────────────────────────────────
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_RUFF }}   # ← personal‑access token
          fetch-depth: 0
          ref: ${{ github.head_ref || github.ref }}

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Ruff
        run: pip install ruff

      - name: Detect changed Python files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          files: |
            **/*.py

      - name: Ruff check (no fix)
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "Changed files: ${{ steps.changed-files.outputs.all_changed_files }}"
          ruff check --exit-zero ${{ steps.changed-files.outputs.all_changed_files }}

      # Auto‑fix runs only for PRs that originate *inside* the repo.
      - name: Ruff auto‑fix
        if: |
          github.event_name == 'pull_request' &&
          github.event.pull_request.head.repo.full_name == github.repository &&
          steps.changed-files.outputs.any_changed == 'true'
        run: |
          ruff check --fix --exit-zero ${{ steps.changed-files.outputs.all_changed_files }}
          ruff format ${{ steps.changed-files.outputs.all_changed_files }}

      - name: Commit Ruff fixes
        if: |
          github.event_name == 'pull_request' &&
          github.event.pull_request.head.repo.full_name == github.repository &&
          steps.changed-files.outputs.any_changed == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          github_token: ${{ secrets.PAT_RUFF }}   # ← same PAT
          commit_message: "🎨 ci: Ruff auto‑fixes"
          commit_user_name: "wisent‑style‑bot"
          commit_user_email: "style-bot@users.noreply.github.com"


