name: CI

on:
  push:                # every branch push
  pull_request:        # every PR
  workflow_dispatch:   # manual run button

# default token stays read‑only; we rely on PAT_RUFF for pushes
permissions:
  contents: read

env:                             # ← visible to *all* jobs
  # Hugging Face auth for tests that download gated models
  HF_TOKEN: ${{ secrets.HUGGING_FACE }}
  HF_HUB_TOKEN: ${{ secrets.HUGGING_FACE }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-cov ruff huggingface_hub

      - name: Run fast tests
        run: |
          pytest -m "not slow and not heavy and not model_download and not docker" -v

      - name: Slow integration test (PRs only)
        if: github.event_name == 'pull_request'
        run: |
          pytest wisent_guard/tests/core/test_benchmark_cli_integration.py \
                -m "not heavy and not model_download and not docker" -v
